services:
  v2ex-feed:
    build:
      context: .
    image: v2ex-feed
    container_name: "v2ex-feed"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
